// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlE7BoKr-ikq-dM8qsB2ANbc2oxOJ4ApQ',
    appId: '1:725782901931:web:9e16ea3715e516f15073ee',
    messagingSenderId: '725782901931',
    projectId: 'circleauth-40820',
    authDomain: 'circleauth-40820.firebaseapp.com',
    databaseURL: 'https://circleauth-40820-default-rtdb.firebaseio.com',
    storageBucket: 'circleauth-40820.appspot.com',
    measurementId: 'G-BW3SMNL5BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlE7BoKr-ikq-dM8qsB2ANbc2oxOJ4ApQ',
    appId: '1:725782901931:android:669a034321fe122d5073ee',
    messagingSenderId: '725782901931',
    projectId: 'circleauth-40820',
    databaseURL: 'https://circleauth-40820-default-rtdb.firebaseio.com',
    storageBucket: 'circleauth-40820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlE7BoKr-ikq-dM8qsB2ANbc2oxOJ4ApQ',
    appId: '1:725782901931:ios:63fb383a8086192b5073ee',
    messagingSenderId: '725782901931',
    projectId: 'circleauth-40820',
    databaseURL: 'https://circleauth-40820-default-rtdb.firebaseio.com',
    storageBucket: 'circleauth-40820.appspot.com',
    iosClientId: '725782901931-6uvh52mq8ii3r05av6rkcrl5cq7bc958.apps.googleusercontent.com',
    iosBundleId: 'com.example.circleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlE7BoKr-ikq-dM8qsB2ANbc2oxOJ4ApQ',
    appId: '1:725782901931:ios:63fb383a8086192b5073ee',
    messagingSenderId: '725782901931',
    projectId: 'circleauth-40820',
    databaseURL: 'https://circleauth-40820-default-rtdb.firebaseio.com',
    storageBucket: 'circleauth-40820.appspot.com',
    iosClientId: '725782901931-6uvh52mq8ii3r05av6rkcrl5cq7bc958.apps.googleusercontent.com',
    iosBundleId: 'com.example.circleApp',
  );
}
